[pytest]
testpaths = tests
markers = 
    smoke: quick tests
    inputs: inputs section
    forms: forms section
    otp: OTP login section
    select: selection section
    buttons: buttons section
    tables: tables section
    changing_attributes: changing attributes section